// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using factopia_backend.DAL.Database;

#nullable disable

namespace factopia_backend.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250406012357_NewQuestionsVraiFake")]
    partial class NewQuestionsVraiFake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("factopia_backend.Domain.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Vrai",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Faux",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 6,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 7,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 8,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 9,
                            Content = "Vrai",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 10,
                            Content = "Faux",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 11,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 12,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 13,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 14,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 15,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 16,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 9
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "REgarde la video ensuite, swipe a droite si c'est vrai !",
                            Title = "TikTok"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fun fact, annecdote et autre conseil.",
                            Title = "Le Saviez-vous ?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Title = "Vrai ou Fake?"
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Regarde et decide si c'est vrai",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Les chats ont cinq orteils à chaque patte avant.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Le sucre rend les enfants hyperactifs.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Le lait aide à réparer les os cassés.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Les éléphants sont les seuls animaux qui ne peuvent pas sauter.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "L'homme a plus de dents que la femme.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "Le miel ne se périme jamais.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "Les oranges contiennent de la vitamine C.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Content = "Le cœur humain est capable de continuer à battre après la mort.",
                            GameTypeId = 3
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Resources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileType = "Image",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/A_1.mp4",
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.UserQuestion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserQuestions", (string)null);
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Answer", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.GameType", "GameType")
                        .WithMany("Questions")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Resource", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "question")
                        .WithMany("Resources")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.UserQuestion", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "Question")
                        .WithMany("UserQuestion")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("factopia_backend.Domain.Models.User", "User")
                        .WithMany("UserQuestion")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.GameType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Resources");

                    b.Navigation("UserQuestion");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.User", b =>
                {
                    b.Navigation("UserQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
