// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using factopia_backend.DAL.Database;

#nullable disable

namespace factopia_backend.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250406102227_AnotherFixSeeds")]
    partial class AnotherFixSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("factopia_backend.Domain.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Vrai",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Faux",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 6,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 7,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 8,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 9,
                            Content = "Vrai",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 10,
                            Content = "Faux",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 11,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 12,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 13,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 14,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 15,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 16,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 17,
                            Content = "Bien vu, nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer cette fausse vidéo. C'est discret, mais si on regarde bien, le mouvement de la patte n'est pas naturel et, quand on zoome, le grain de l'image est typique de ce que Sora est capable de produire. ",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 18,
                            Content = "Désolé, vous vous êtes trompé, nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer cette fausse vidéo. C'est discret, mais si on regarde bien, le mouvement de la patte n'est pas naturel et, quand on zoome, le grain de l'image est typique de ce que Sora est capable de produire. ",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 19,
                            Content = "Bien vu, il s'agit bien d'une vraie vidéo proposée par Getty Images,",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 20,
                            Content = "Désolé, vous vous êtes trompé, il s'agit en fait un clip vidéo proposé par Getty Images,",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 21,
                            Content = "Bien vu, nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer cette fausse vidéo. Un détail permettait de déceler le fake : le bras d'une personne assise à droite de l'image a esquissé un mouvement pas très naturel. Certaines pailles dans les verres sur le plateau bougent bizarrement aussi. ",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 22,
                            Content = "Désolé, vous vous êtes trompé, nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer cette fausse vidéo. Certains détails auraient pu vous mettre sur la piste  : le bras d'une personne assise à droite de l'image a esquissé un mouvement pas très naturel. Certaines pailles dans les verres sur le plateau bougent bizarrement aussi. ",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 23,
                            Content = "Bien vu, il s'agit bien d'une vraie vidéo proposée par Getty Images,",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 24,
                            Content = "Désolé, vous vous êtes trompé, il s'agit en fait un clip vidéo proposé par Getty Images,",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 25,
                            Content = "Bravo, décidément, on ne vous la fait pas à vous!. Il faut dire que c'était facile avec le téléphone gigantesque en arrière-plan et les mains qui semblent à peine toucher le clavier. Nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer cette vidéo,",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 26,
                            Content = "Désolé, vous vous êtes trompé, vous auriez pu trouver, si vous aviez remarqué le téléphone gigantesque en arrière-plan et les mains qui semblent à peine toucher le clavier, vous auriez pu trouver. Nous avons utilisé Sora, l'outil de création de vidéos mis au point par Open AI pour générer la première vidéo.",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 27,
                            Content = "Bien vu, il s'agit bien d'une vraie vidéo proposée par Getty Images,",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 28,
                            Content = "Désolé, vous vous êtes trompé, il s'agit en fait un clip vidéo proposé par Getty Images,",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 29,
                            Content = "Bien vu ! Vous avez peut-être été frappé par l'aspect trop lisse des bâtiments et par le drapeau américain au premier plan qui bouge avec un mouvement pas très naturel. Encore une fois, c'est l'oeuvre de Sora, tandis que l'autre vidéo vient de Getty Images.",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 30,
                            Content = "Désolé, vous vous êtes trompé, vous auriez pu deviner, si vous aviez remarqué  l'aspect trop lisse des bâtiments et par le drapeau américain au premier plan qui bouge avec un mouvement pas très naturel. Encore une fois, c'est l'oeuvre de Sora,",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 31,
                            Content = "Bien vu, il s'agit bien d'une vraie vidéo proposée par Getty Images,",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 32,
                            Content = "Désolé, vous vous êtes trompé, il s'agit en fait un clip vidéo proposé par Getty Images,",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 33,
                            Content = "Bien vu !  Ce jeune homme est le résultat de l'imagination de l'IA",
                            IsCorrect = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 34,
                            Content = "Désolé, vous vous êtes trompé ! Ce jeune homme est le résultat de l'imagination de l'IA",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 35,
                            Content = "Bien vu, il s'agit bien d'une vidéo probablement tournée sur un trampoline, qui vient de Getty Images.",
                            IsCorrect = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 36,
                            Content = "Désolé, il s'agit en faite d'une vidéo de Getty Images probablement tournée sur un trampoline.",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 37,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 38,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 39,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 40,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 41,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 42,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 43,
                            Content = "Vrai",
                            IsCorrect = true,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 44,
                            Content = "Faux",
                            IsCorrect = false,
                            QuestionId = 23
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "REgarde la video ensuite, swipe a droite si c'est vrai !",
                            Title = "TikTok"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fun fact, annecdote et autre conseil.",
                            Title = "Le Saviez-vous ?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Title = "Vrai ou Fake?"
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Regarde et decide si c'est vrai",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Les chats ont cinq orteils à chaque patte avant.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Le sucre rend les enfants hyperactifs.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Le lait aide à réparer les os cassés.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Les éléphants sont les seuls animaux qui ne peuvent pas sauter.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "L'homme a plus de dents que la femme.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "Le miel ne se périme jamais.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "Les oranges contiennent de la vitamine C.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Content = "Le cœur humain est capable de continuer à battre après la mort.",
                            GameTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Cette vidéo est-elle fake ou réelle ?",
                            GameTypeId = 1
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Resources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/1_Fake.mp4",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 2,
                            FileType = "Video",
                            IsCorrect = true,
                            Name = "A_1.mp4",
                            Path = "/videos/1_Real.mp4",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 3,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/2_Fake.mp4",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 4,
                            FileType = "Video",
                            IsCorrect = true,
                            Name = "A_1.mp4",
                            Path = "/videos/2_Real.mp4",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 5,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/3_Fake.mp4",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 6,
                            FileType = "Video",
                            IsCorrect = true,
                            Name = "A_1.mp4",
                            Path = "/videos/3_Real.mov",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 7,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/4_Fake.mp4",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 8,
                            FileType = "Video",
                            IsCorrect = true,
                            Name = "A_1.mp4",
                            Path = "/videos/4_Real.mp4",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 9,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/5_Fake.mp4",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 10,
                            FileType = "Video",
                            IsCorrect = true,
                            Name = "A_1.mp4",
                            Path = "/videos/5_Real.mp4",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 11,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/LumaAIdroppedaSoracompetitor–Dream Machine-text-to-videogeneratorthatsopentoALLai.mp4.mp4",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 12,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/ThisisnotMorganFreemanADeepfakeSingularity.mp4",
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 13,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/TrumpGetsaKimJongUnHaircut–PutinCantStopLaughing.mp4",
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 14,
                            FileType = "Video",
                            IsCorrect = false,
                            Name = "A_1.mp4",
                            Path = "/videos/ViralAIVideoTrumpHarrisRomanceAheadofUSElection.mp4",
                            QuestionId = 23
                        });
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.UserQuestion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserQuestions", (string)null);
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Answer", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.GameType", "GameType")
                        .WithMany("Questions")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Resource", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "question")
                        .WithMany("Resources")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.UserQuestion", b =>
                {
                    b.HasOne("factopia_backend.Domain.Models.Question", "Question")
                        .WithMany("UserQuestion")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("factopia_backend.Domain.Models.User", "User")
                        .WithMany("UserQuestion")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.GameType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Resources");

                    b.Navigation("UserQuestion");
                });

            modelBuilder.Entity("factopia_backend.Domain.Models.User", b =>
                {
                    b.Navigation("UserQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
